// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LQ1i6W7bwsE7fuZhndYBzlGEYCFKpsk',
    appId: '1:340477945855:web:6cbd47f923987dbf2de9ca',
    messagingSenderId: '340477945855',
    projectId: 'attendance-8ede1',
    authDomain: 'attendance-8ede1.firebaseapp.com',
    storageBucket: 'attendance-8ede1.firebasestorage.app',
    measurementId: 'G-KSM20FCH0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-4nC8PlY7Aa0w0ndSV9BreYAXuGTX52A',
    appId: '1:340477945855:android:505a411b8dbc78ed2de9ca',
    messagingSenderId: '340477945855',
    projectId: 'attendance-8ede1',
    storageBucket: 'attendance-8ede1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbiQMzSjzrmFw0-rJSALVLGkUcWLJJwo',
    appId: '1:340477945855:ios:1e3535f59fb237642de9ca',
    messagingSenderId: '340477945855',
    projectId: 'attendance-8ede1',
    storageBucket: 'attendance-8ede1.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0LQ1i6W7bwsE7fuZhndYBzlGEYCFKpsk',
    appId: '1:340477945855:web:f41838c4f34710a72de9ca',
    messagingSenderId: '340477945855',
    projectId: 'attendance-8ede1',
    authDomain: 'attendance-8ede1.firebaseapp.com',
    storageBucket: 'attendance-8ede1.firebasestorage.app',
    measurementId: 'G-F33ZFX5FYH',
  );

}