// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT11LcUIS-Z6oDXeGFRfS6jAVnStfX_Rg',
    appId: '1:686163073951:web:77e283b04ce774dc777baa',
    messagingSenderId: '686163073951',
    projectId: 'attendance-d520d',
    authDomain: 'attendance-d520d.firebaseapp.com',
    storageBucket: 'attendance-d520d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABEwpFydwvbI0c8muVoXQuzMHZFHQbxVI',
    appId: '1:686163073951:android:6c5c46272e66539a777baa',
    messagingSenderId: '686163073951',
    projectId: 'attendance-d520d',
    storageBucket: 'attendance-d520d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEtGueeC_Xqfl6FcomCuLs8rlq1i3XYyE',
    appId: '1:686163073951:ios:9e0436b13db4c102777baa',
    messagingSenderId: '686163073951',
    projectId: 'attendance-d520d',
    storageBucket: 'attendance-d520d.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT11LcUIS-Z6oDXeGFRfS6jAVnStfX_Rg',
    appId: '1:686163073951:web:e2e70717f3ee3f55777baa',
    messagingSenderId: '686163073951',
    projectId: 'attendance-d520d',
    authDomain: 'attendance-d520d.firebaseapp.com',
    storageBucket: 'attendance-d520d.firebasestorage.app',
  );
}
